###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "DaniiiielBastidas",
    "cedula": "001",
    "age": "30",
    "email": "daniel@correo.com",
    "dir": "34qbc"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
PUT http://localhost:9000/api/users/cedula/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Daniel Bastidas",
    "cedula": "111",
    "age": "30",
    "email": "daniel@correo.com",
    "dir": "34qbc"
}