###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jesus Bastidas",
    "cedula": "10616468564",
    "age": "35",
    "email": "jesus@correo.com",
    "dir": "34asd"
}